name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jmo808/technitium-dns:$(date +%s)
    - name: Push the Docker image
      run: docker push jmo808/technitium-dns:$(date +%s)
